# netlify.toml
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

# Handle routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable settings
[context.production.environment]
  VITE_NODE_ENV = "production"
  VITE_BASE_URL = "https://omni-app-mern.onrender.com" 