[build]
  base = "."
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm install -g typescript && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18" 