[build]
  base = "."
  publish = "frontend/dist"
  command = "./build.sh"
  functions = "netlify/functions"

# Redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/api/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"] 