[build]
  base = "."
  publish = "frontend/dist"
  command = "cd frontend && npm install --legacy-peer-deps && npm install -g typescript && (npx tsc -b || true) && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "20" 