[build]
  base = "."
  publish = "frontend/dist"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18"
  
[context.production.environment]
  VITE_NODE_ENV = "production"
  VITE_BASE_URL = "https://omni-app-mern.onrender.com" 