[build]
  base = "."
  publish = "frontend/dist"
  command = "./build.sh"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"] 